image:
  repository: swr.cn-north-4.myhuaweicloud.com/flex/dbay-agent-api
  tag: "0.1.0"
  pullPolicy: IfNotPresent

lakebase:
  apiBaseUrl: "https://api.dbay.cloud:8443/api/v1"
  serviceTokenSecret:
    enabled: false
    name: dbay-agent-lakebase-token
    key: token

database:
  url: ""
  user: ""
  password: ""
  driver: ""
  ddlAuto: "update"

service:
  type: LoadBalancer
  port: 8082
  targetPort: 8080
  annotations: {}
  elb:
    id: "46b20c38-5c54-4781-9f00-d25d8c1717a8"
    class: performance
    autocreate: ""

replicaCount: 1

imagePullSecrets:
  - name: swr-secret

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
