{{- if .Values.database.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dbay-agent.fullname" . }}-secrets
  labels:
    {{- include "dbay-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-password: {{ .Values.database.password | quote }}
{{- end }}
