apiVersion: v1
kind: Service
metadata:
  name: {{ include "dbay-agent.fullname" . }}
  labels:
    {{- include "dbay-agent.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.service.elb.autocreate .Values.service.elb.id }}
  annotations:
    {{- if .Values.service.elb.id }}
    kubernetes.io/elb.id: {{ .Values.service.elb.id | quote }}
    {{- end }}
    {{- if .Values.service.elb.class }}
    kubernetes.io/elb.class: {{ .Values.service.elb.class | quote }}
    {{- end }}
    {{- if .Values.service.elb.autocreate }}
    kubernetes.io/elb.autocreate: {{ .Values.service.elb.autocreate | quote }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "dbay-agent.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
