ALTER TABLE tenants ADD COLUMN max_databases INTEGER NOT NULL DEFAULT 3;
ALTER TABLE tenants ADD COLUMN max_storage_gb INTEGER NOT NULL DEFAULT 50;
ALTER TABLE tenants ADD COLUMN max_compute_cu INTEGER NOT NULL DEFAULT 4;
