package com.lakeon.knowledge;

public enum KbWriteTaskType {
    DOCUMENT_PARSE,
    BATCH_DOCUMENT_PARSE,
    RECHUNK,
    EDIT_CHUNK,
    DELETE_CHUNK,
    CREATE_CHUNK,
    RECHUNK_ROLLBACK,
    DELETE_DOCUMENT_CHUNKS,
    DOCUMENT_SUMMARIZE,
    KB_SUMMARIZE,
    WIKI_UPDATE
}
